if (NOT FLASH_SIZE)
    set (FLASH_SIZE 32768)
endif (NOT FLASH_SIZE)

if (NOT FLASH_PAGE_SIZE)
    set (FLASH_PAGE_SIZE 1024)
endif (NOT FLASH_PAGE_SIZE)

if (NOT RAM_SIZE)
    set (RAM_SIZE 20480)
endif (NOT RAM_SIZE)

if (NOT FLASH_OFFSET)
    set (FLASH_OFFSET 0)
endif (NOT FLASH_OFFSET)
